sudo: false
language: python
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.6
    env: TOXENV=py36
install: pip install tox
script: tox
deploy:
  provider: pypi
  user: gtema
  # distributions: sdist bdist_wheel
  password:
    secure: N4s5CTaWGanNJx/yxSsabAyk3JnpnzRQRPBjQKLSsBF40gjpOU5ui46BzKa1BCTUxitRbwyZlf1joumKdfgoOW4yIec0jsj8pAfVJo6ldwvMhQd51QCQfoKmuvPy7i8X5pLWzaYFtIzZR7eCztcwAGfqnYeRn0KO9u2pGUp1Bx/9f92qQ2K2NGM17OMYlWDL+Shb4YVOsOQHtTSc7KBjolUKAwibbX/ENGkysjsyOGOIaTYb10gANoBqxr5/3M+kzwR2EZkrkzU4NgeloFAM7sOt4WnsZwLHICzgwqW+bKMZ00/jOdB+sqMiErxXPG/HWLdEae73TN3lQYjc6+RHeh4V+VFhwvOZ45XRbJ0lDndjGNRYjsamOob1YaY5WsqBoiS7RfLAysbm5Vh42RhsXLoOUe3A2v92ryYH22KqraRDYYKFf0/3h18TsR3bBj4neZB0F6W2fSaGujKAjWk++BwsLwhS7mY638QUf7JR4piMXILTnBVkTGK7PEv1RiMtc+bv5lkdIowF4Bddc2OqjiSbMjhR8aUVZ4Aa64aJK6uez2L2DbHiNC5UUwjFmiS0hoRJYJSgv/qwkHJnfrQDxVCJ0aVrfqBkoWeY0qyDdoeYTubDhVZO88wuvXoazPei+oj7gJDvVlVPa/RnmQu9Sxoqb9vYn0mT7hyBKL+DP/0=
  # skip_cleanup: true
  on:
    # tags: true
    condition: "$TOXENV = py36"
    branch: master
